# Generated by Django 5.1.4 on 2024-12-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('full_name', 'Full name'), ('email', 'Email'), ('domain_name', 'Domain name'), ('phone_number', 'Phone number'), ('company_name', 'Company name'), ('text', 'Text'), ('integer', 'Integer value'), ('address', 'Address'), ('date', 'Date')], max_length=20)),
                ('order', models.IntegerField()),
                ('extra_args', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('separator', models.CharField(choices=[('comma', 'Comma (,)'), ('semicolon', 'Semicolon (;)'), ('tab', 'Tab (\\t)'), ('pipe', 'Pipe (|)'), ('space', 'Space ( )'), ('colon', 'Colon (:)')], default='comma', max_length=20)),
                ('string_char', models.CharField(choices=[('double_quote', 'Double-quote (")'), ('single_quote', "Single-quote(')"), ('backtick', 'Backtick (`)'), ('square_brackets', 'Square brackets ([ ])'), ('curly_brackets', 'Curly brackets ({ })'), ('angle_brackets', 'Angle brackets (< >)'), ('parentheses', 'Parentheses (( ))')], default='double_quote', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
